version: '3'
services:
  d-server-minio:
    image: minio/minio
    container_name: d-server-minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    ports:
      - '9000:9000'
    volumes:
      - d_vol:/data
      - d_vol:/root/.minio
    command: server /data  
  d-cron:
    build: docker-files-one/docker_cron
    container_name: d-cron
    restart: always
    volumes:
      - d_vol:/app/capturas
  d-server-db:
    image: postgres:11
    container_name: d-server-db
    restart: always
    networks:
      - d_network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=d_db
    ports:
      - '5432:5432'
    volumes:
      - d_data:/var/lib/postgresql/data
  d-server-one:
    build: docker-files/docker_one
    container_name: d-server-one
    restart: always
    volumes:
      - d_vol:/app/capturas
    ports:
      - '8089:8089'
    networks:
      - d_network
    depends_on:
      - 'd-server-db'
  d-server-front:
    build: docker-files/d-front
    container_name: d-server-front
    restart: always
    ports:
      - '90:80'
    networks:
      - d_network
    depends_on:
      - 'd-server-one'
volumes:
  d_data:
  d_vol:
networks:
  d_network:
    driver: bridge
